name: kksm_lec_flutter_lab
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
#  sdk: '>=2.19.2 <3.0.0'
  sdk: '>=2.19.2 <3.7.3'

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  json_annotation: ^4.8.1
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - resources/
    - resources/images/
