name: kksm_lec_flutter_lab
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  #  sdk: '>=2.19.2 <3.0.0'
  sdk: '>=2.19.2 <3.7.3'

dependencies:
  bloc: ^8.0.3
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  geolocator: ^8.2.1
  get: ^4.6.5
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - resources/
    - resources/images/
